Repository Breakthrough/PySceneDetect, pull requests merged in 2019-11, with the labels that each got.

#127 Fixed read_frame #126.
  scenedetect/video_manager.py
Labels: bug, status: completed

#129 Add `save-images` option for ignoring a number of frames at start/end.
  scenedetect/cli/__init__.py
  scenedetect/cli/context.py
Labels: feature, status: completed

#128 Modify `--min-duration` arguments to accept a timecode instead of frame numbers
  scenedetect/cli/__init__.py
Labels: enhancement, status: in progress
